name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "db"
database_id = "f02e6a66-080f-4ac6-9024-5151403b1619"

[[kv_namespaces]]
binding = "kv"
id = "c2597d4af99d4b24be9b685526d26573"

# [[r2_buckets]]  ← Uncomment jika Anda menggunakan R2

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[[routes]]
pattern = "*.expl.web.id/*"
zone_id = "14f7bb5ebebeaf50fb33981dcfede562"

[vars]
orm_log = false
domain = '["expl.web.id"]'
admin = "admin@expl.web.id"
# jwt_secret jangan taruh di sini! Gunakan wrangler secret put
